# Generated by Django 4.1.6 on 2023-02-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Post Title')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photography')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Changed date')),
                ('publish', models.BooleanField(default=True, verbose_name='Post status')),
                ('views', models.IntegerField(default=0, verbose_name='Number of views')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
