# Generated by Django 4.1.6 on 2023-03-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_author_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='article',
            new_name='post',
        ),
    ]
